### ISSUE TITLE
Needs a better installation guide

### ISSUE THREAD

**Issue by pporada-gl** [dowjones/slack-slash-jira#1]
I am not a nodejs developer, as a result I am not sure how to use your code.
- What version of Node is required?
- Can you show a full config and possibly a config for a Jira behind a proxy?
- Can you show what the Slack "slash command" service configuration should look like?

**Comment by scott2449** [comment]
What do you feel is missing? You have to read the https://github.com/dowjones/slack-slash and https://api.slack.com/slash-commands documentation as well to fully understand what this library is about. That's clearly stated in the readme. Also I believe that is the full config. There is only 80 lines of very readable code (and config is right at the top if you wanted to double check).

**Comment by scott2449** [comment]
@adamgruber now may be the time to set up some travis builds. That would benefit you and as a side bonus make the supported versions super clear.

**Comment by adamgruber** [comment]
@scott2449 Added eslint and travis builds in https://github.com/dowjones/slack-slash-jira/pull/2

**Comment by scott2449** [comment]
:+1:
